### ISSUE TITLE
Incompatible with PHP 7.1

### ISSUE THREAD

**Issue by stu177** [firebearstudio/importexportfree#22]
Currently requires:

`php: ~5.5.0|~5.6.0|~7.0.0`

So it's throwing:
                                                                                                    
```
[InvalidArgumentException]                                                                          
Could not find package firebear/importexportfree at any version matching your PHP version 7.1.10.0
```

Is this because of breaking changes in the new PHP version or just the requirement on the package hasn't been updated to 7.1?

**Comment by biotech** [comment]
This is fixed now , works great on PHP 7.1 https://github.com/firebearstudio/importexportfree/blob/master/composer.json

**Comment by stu177** [comment]
Can you tag this so it gets updated in packagist? In the latest version 1.0.10, this is still broken.
